### ISSUE TITLE
LinkedGeoData not getting fetched by app

### ISSUE THREAD

**Issue by m31r2701** [gchq/LD-Explorer#24]
**Describe the bug**
One of the remote sources available in the catalogue is LinkedGeoData. Unfortunately, errors are returned saying access control checks failed and that it is not possible to request the resource.

**To Reproduce**

1. Go to [Catalog](https://gchq.github.io/LD-Explorer/sources/catalog)
2. Click on 'Add' next to `LinkedGeoData` 
3. Go to [Explore](https://gchq.github.io/LD-Explorer/explore) and click on, e.g., [Classes](https://gchq.github.io/LD-Explorer/explore/classes)
4. Observe errors thrown in [Logs](https://gchq.github.io/LD-Explorer/logs) / DevTools console

**Expected behavior**
Would expect the data to be loaded from the remote resource into the application

**Screenshots**
Error messages in the logs:

<img width="1680" alt="Screenshot 2024-09-14 at 17 03 05" src="https://github.com/user-attachments/assets/bc93855b-abc2-4dd7-b1db-950e4276eaa8">

Error messages in the console:

<img width="1680" alt="Screenshot 2024-09-14 at 17 03 53" src="https://github.com/user-attachments/assets/99b6d41e-6fbc-4856-9d55-06c9f3abc3a5">

**Desktop**

- OS: MacOS 14.6
- Browser: Safari
- Version: 17.6

**Comment by GCHQDeveloper81** [comment]
Thanks for raising - I believe just from looking at the error there that this is probably because the remote source is serving http and the site itself is served out of https, so it should just be a case of updating the URL to `https`.
